version: '2'
services:
  ulvm:
    build:
      context: .
    image: ulvm:latest
    volumes:
     - .:/usr/src/app
     - /var/run/docker.sock:/var/run/docker.sock
networks:
  default:
    external:
      name: 'bridge'
